// Generated from free-exercise-db (https://github.com/yuhonas/free-exercise-db, public domain / Unlicense):
// instructions and start/end photos. Names and cues are our own.
import { Exercise } from './types';

const IMAGE_BASE = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/';

function images(datasetId: string): Exercise['media'] {
  return [0, 1].map(i => ({ type: 'image' as const, src: `${IMAGE_BASE}${datasetId}/${i}.jpg` }));
}

export const DEFAULT_EXERCISES: Exercise[] = [
  {
    id: 'default-bench-press',
    name: 'Bench Press',
    muscleGroup: 'chest',
    equipment: 'barbell',
    notes: 'Shoulder blades squeezed together, feet planted, lower the bar to mid-chest',
    media: images('Barbell_Bench_Press_-_Medium_Grip'),
    instructions: [
      'Lie back on a flat bench. Using a medium width grip (a grip that creates a 90-degree angle in the middle of the movement between the forearms and the upper arms), lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.',
      'From the starting position, breathe in and begin coming down slowly until the bar touches your middle chest.',
      'After a brief pause, push the bar back to the starting position as you breathe out. Focus on pushing the bar using your chest muscles. Lock your arms and squeeze your chest in the contracted position at the top of the motion, hold for a second and then start coming down slowly again. Tip: Ideally, lowering the weight should take about twice as long as raising it.',
      'Repeat the movement for the prescribed amount of repetitions.',
      'When you are done, place the bar back in the rack.',
    ],
  },
  {
    id: 'default-incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    muscleGroup: 'chest',
    equipment: 'dumbbell',
    notes: 'Bench at 30–45°, elbows about 45° from the body',
    media: images('Incline_Dumbbell_Press'),
    instructions: [
      'Lie back on an incline bench with a dumbbell in each hand atop your thighs. The palms of your hands will be facing each other.',
      'Then, using your thighs to help push the dumbbells up, lift the dumbbells one at a time so that you can hold them at shoulder width.',
      'Once you have the dumbbells raised to shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. This will be your starting position.',
      'Be sure to keep full control of the dumbbells at all times. Then breathe out and push the dumbbells up with your chest.',
      'Lock your arms at the top, hold for a second, and then start slowly lowering the weight. Tip Ideally, lowering the weights should take about twice as long as raising them.',
      'Repeat the movement for the prescribed amount of repetitions.',
      'When you are done, place the dumbbells back on your thighs and then on the floor. This is the safest manner to release the dumbbells.',
    ],
  },
  {
    id: 'default-chest-dip',
    name: 'Chest Dip',
    muscleGroup: 'chest',
    equipment: 'bodyweight',
    notes: 'Lean forward and let the elbows flare slightly to bias the chest',
    media: images('Dips_-_Chest_Version'),
    instructions: [
      'For this exercise you will need access to parallel bars. To get yourself into the starting position, hold your body at arms length (arms locked) above the bars.',
      'While breathing in, lower yourself slowly with your torso leaning forward around 30 degrees or so and your elbows flared out slightly until you feel a slight stretch in the chest.',
      'Once you feel the stretch, use your chest to bring your body back to the starting position as you breathe out. Tip: Remember to squeeze the chest at the top of the movement for a second.',
      'Repeat the movement for the prescribed amount of repetitions.',
    ],
  },
  {
    id: 'default-cable-crossover',
    name: 'Cable Crossover',
    muscleGroup: 'chest',
    equipment: 'cable',
    notes: 'Slight bend in the elbows, squeeze the hands together in front of the chest',
    media: images('Cable_Crossover'),
    instructions: [
      'To get yourself into the starting position, place the pulleys on a high position (above your head), select the resistance to be used and hold the pulleys in each hand.',
      'Step forward in front of an imaginary straight line between both pulleys while pulling your arms together in front of you. Your torso should have a small forward bend from the waist. This will be your starting position.',
      'With a slight bend on your elbows in order to prevent stress at the biceps tendon, extend your arms to the side (straight out at both sides) in a wide arc until you feel a stretch on your chest. Breathe in as you perform this portion of the movement. Tip: Keep in mind that throughout the movement, the arms and torso should remain stationary; the movement should only occur at the shoulder joint.',
      'Return your arms back to the starting position as you breathe out. Make sure to use the same arc of motion used to lower the weights.',
      'Hold for a second at the starting position and repeat the movement for the prescribed amount of repetitions.',
    ],
  },
  {
    id: 'default-machine-chest-press',
    name: 'Machine Chest Press',
    muscleGroup: 'chest',
    equipment: 'machine',
    notes: 'Handles level with mid-chest, don\'t let the shoulders roll forward',
    media: images('Machine_Bench_Press'),
    instructions: [
      'Sit down on the Chest Press Machine and select the weight.',
      'Step on the lever provided by the machine since it will help you to bring the handles forward so that you can grab the handles and fully extend the arms.',
      'Grab the handles with a palms-down grip and lift your elbows so that your upper arms are parallel to the floor to the sides of your torso. Tip: Your forearms will be pointing forward since you are grabbing the handles. Once you bring the handles forward and extend the arms you will be at the starting position.',
      'Now bring the handles back towards you as you breathe in.',
      'Push the handles away from you as you flex your pecs and you breathe out. Hold the contraction for a second before going back to the starting position.',
      'Repeat for the recommended amount of reps.',
      'When finished step on the lever again and slowly get the handles back to their original place.',
    ],
  },
  {
    id: 'default-push-up',
    name: 'Push-Up',
    muscleGroup: 'chest',
    equipment: 'bodyweight',
    notes: 'Body in a straight line, chest to just above the floor',
    media: images('Pushups'),
    instructions: [
      'Lie on the floor face down and place your hands about 36 inches apart while holding your torso up at arms length.',
      'Next, lower yourself downward until your chest almost touches the floor as you inhale.',
      'Now breathe out and press your upper body back up to the starting position while squeezing your chest.',
      'After a brief pause at the top contracted position, you can begin to lower yourself downward again for as many repetitions as needed.',
    ],
  },
  {
    id: 'default-deadlift',
    name: 'Deadlift',
    muscleGroup: 'back',
    equipment: 'barbell',
    notes: 'Bar over mid-foot, flat back, push the floor away',
    media: images('Barbell_Deadlift'),
    instructions: [
      'Stand in front of a loaded barbell.',
      'While keeping the back as straight as possible, bend your knees, bend forward and grasp the bar using a medium (shoulder width) overhand grip. This will be the starting position of the exercise. Tip: If it is difficult to hold on to the bar with this grip, alternate your grip or use wrist straps.',
      'While holding the bar, start the lift by pushing with your legs while simultaneously getting your torso to the upright position as you breathe out. In the upright position, stick your chest out and contract the back by bringing the shoulder blades back. Think of how the soldiers in the military look when they are in standing in attention.',
      'Go back to the starting position by bending at the knees while simultaneously leaning the torso forward at the waist while keeping the back straight. When the weights on the bar touch the floor you are back at the starting position and ready to perform another repetition.',
      'Perform the amount of repetitions prescribed in the program.',
    ],
  },
  {
    id: 'default-pull-up',
    name: 'Pull-Up',
    muscleGroup: 'back',
    equipment: 'bodyweight',
    notes: 'Start from a dead hang, pull the chest towards the bar',
    media: images('Pullups'),
    instructions: [
      'Grab the pull-up bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than your shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.',
      'As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.',
      'Pull your torso up until the bar touches your upper chest by drawing the shoulders and the upper arms down and back. Exhale as you perform this portion of the movement. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar.',
      'After a second on the contracted position, start to inhale and slowly lower your torso back to the starting position when your arms are fully extended and the lats are fully stretched.',
      'Repeat this motion for the prescribed amount of repetitions.',
    ],
  },
  {
    id: 'default-barbell-row',
    name: 'Barbell Row',
    muscleGroup: 'back',
    equipment: 'barbell',
    notes: 'Hinge to about 45°, pull the bar to the lower ribs',
    media: images('Bent_Over_Barbell_Row'),
    instructions: [
      'Holding a barbell with a pronated grip (palms facing down), bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The barbell should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position.',
      'Now, while keeping the torso stationary, breathe out and lift the barbell to you. Keep the elbows close to the body and only use the forearms to hold the weight. At the top contracted position, squeeze the back muscles and hold for a brief pause.',
      'Then inhale and slowly lower the barbell back to the starting position.',
      'Repeat for the recommended amount of repetitions.',
    ],
  },
  {
    id: 'default-lat-pulldown',
    name: 'Lat Pulldown',
    muscleGroup: 'back',
    equipment: 'cable',
    notes: 'Lean back slightly, pull the bar to the upper chest',
    media: images('Wide-Grip_Lat_Pulldown'),
    instructions: [
      'Sit down on a pull-down machine with a wide bar attached to the top pulley. Make sure that you adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.',
      'Grab the bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.',
      'As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.',
      'As you breathe out, bring the bar down until it touches your upper chest by drawing the shoulders and the upper arms down and back. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the bar; therefore do not try to pull down the bar using the forearms.',
      'After a second at the contracted position squeezing your shoulder blades together, slowly raise the bar back to the starting position when your arms are fully extended and the lats are fully stretched. Inhale during this portion of the movement.',
      'Repeat this motion for the prescribed amount of repetitions.',
    ],
  },
  {
    id: 'default-seated-cable-row',
    name: 'Seated Cable Row',
    muscleGroup: 'back',
    equipment: 'cable',
    notes: 'Chest up, pull to the stomach, squeeze the shoulder blades',
    media: images('Seated_Cable_Rows'),
    instructions: [
      'For this exercise you will need access to a low pulley row machine with a V-bar. Note: The V-bar will enable you to have a neutral grip where the palms of your hands face each other. To get into the starting position, first sit down on the machine and place your feet on the front platform or crossbar provided making sure that your knees are slightly bent and not locked.',
      'Lean over as you keep the natural alignment of your back and grab the V-bar handles.',
      'With your arms extended pull back until your torso is at a 90-degree angle from your legs. Your back should be slightly arched and your chest should be sticking out. You should be feeling a nice stretch on your lats as you hold the bar in front of you. This is the starting position of the exercise.',
      'Keeping the torso stationary, pull the handles back towards your torso while keeping the arms close to it until you touch the abdominals. Breathe out as you perform that movement. At that point you should be squeezing your back muscles hard. Hold that contraction for a second and slowly go back to the original position while breathing in.',
      'Repeat for the recommended amount of repetitions.',
    ],
  },
  {
    id: 'default-one-arm-dumbbell-row',
    name: 'One-Arm Dumbbell Row',
    muscleGroup: 'back',
    equipment: 'dumbbell',
    notes: 'Flat back, pull the dumbbell towards the hip',
    media: images('One-Arm_Dumbbell_Row'),
    instructions: [
      'Choose a flat bench and place a dumbbell on each side of it.',
      'Place the right leg on top of the end of the bench, bend your torso forward from the waist until your upper body is parallel to the floor, and place your right hand on the other end of the bench for support.',
      'Use the left hand to pick up the dumbbell on the floor and hold the weight while keeping your lower back straight. The palm of the hand should be facing your torso. This will be your starting position.',
      'Pull the resistance straight up to the side of your chest, keeping your upper arm close to your side and keeping the torso stationary. Breathe out as you perform this step. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. Also, make sure that the force is performed with the back muscles and not the arms. Finally, the upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the dumbbell; therefore do not try to pull the dumbbell up using the forearms.',
      'Lower the resistance straight down to the starting position. Breathe in as you perform this step.',
      'Repeat the movement for the specified amount of repetitions.',
      'Switch sides and repeat again with the other arm.',
    ],
  },
  {
    id: 'default-overhead-press',
    name: 'Overhead Press',
    muscleGroup: 'shoulders',
    equipment: 'barbell',
    notes: 'Glutes tight, press straight up and move the head through at the top',
    media: images('Standing_Military_Press'),
    instructions: [
      'Start by placing a barbell that is about chest high on a squat rack. Once you have selected the weights, grab the barbell using a pronated (palms facing forward) grip. Make sure to grip the bar wider than shoulder width apart from each other.',
      'Slightly bend the knees and place the barbell on your collar bone. Lift the barbell up keeping it lying on your chest. Take a step back and position your feet shoulder width apart from each other.',
      'Once you pick up the barbell with the correct grip length, lift the bar up over your head by locking your arms. Hold at about shoulder level and slightly in front of your head. This is your starting position.',
      'Lower the bar down to the collarbone slowly as you inhale.',
      'Lift the bar back up to the starting position as you exhale.',
      'Repeat for the recommended amount of repetitions.',
    ],
  },
  {
    id: 'default-dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    muscleGroup: 'shoulders',
    equipment: 'dumbbell',
    notes: 'Lower to ear height, press without arching the lower back',
    media: images('Dumbbell_Shoulder_Press'),
    instructions: [
      'While holding a dumbbell in each hand, sit on a military press bench or utility bench that has back support. Place the dumbbells upright on top of your thighs.',
      'Now raise the dumbbells to shoulder height one at a time using your thighs to help propel them up into position.',
      'Make sure to rotate your wrists so that the palms of your hands are facing forward. This is your starting position.',
      'Now, exhale and push the dumbbells upward until they touch at the top.',
      'Then, after a brief pause at the top contracted position, slowly lower the weights back down to the starting position while inhaling.',
      'Repeat for the recommended amount of repetitions.',
    ],
  },
  {
    id: 'default-lateral-raise',
    name: 'Lateral Raise',
    muscleGroup: 'shoulders',
    equipment: 'dumbbell',
    notes: 'Lead with the elbows, stop at shoulder height',
    media: images('Side_Lateral_Raise'),
    instructions: [
      'Pick a couple of dumbbells and stand with a straight torso and the dumbbells by your side at arms length with the palms of the hand facing you. This will be your starting position.',
      'While maintaining the torso in a stationary position (no swinging), lift the dumbbells to your side with a slight bend on the elbow and the hands slightly tilted forward as if pouring water in a glass. Continue to go up until you arms are parallel to the floor. Exhale as you execute this movement and pause for a second at the top.',
      'Lower the dumbbells back down slowly to the starting position as you inhale.',
      'Repeat for the recommended amount of repetitions.',
    ],
  },
  {
    id: 'default-face-pull',
    name: 'Face Pull',
    muscleGroup: 'shoulders',
    equipment: 'cable',
    notes: 'Rope at face height, pull apart towards the ears',
    media: images('Face_Pull'),
    instructions: [
      'Facing a high pulley with a rope or dual handles attached, pull the weight directly towards your face, separating your hands as you do so. Keep your upper arms parallel to the ground.',
    ],
  },
  {
    id: 'default-reverse-fly',
    name: 'Reverse Fly',
    muscleGroup: 'shoulders',
    equipment: 'dumbbell',
    notes: 'Hinge forward, raise the arms out wide with soft elbows',
    media: images('Reverse_Flyes'),
    instructions: [
      'To begin, lie down on an incline bench with the chest and stomach pressing against the incline. Have the dumbbells in each hand with the palms facing each other (neutral grip).',
      'Extend the arms in front of you so that they are perpendicular to the angle of the bench. The legs should be stationary while applying pressure with the ball of your toes. This is the starting position.',
      'Maintaining the slight bend of the elbows, move the weights out and away from each other (to the side) in an arc motion while exhaling. Tip: Try to squeeze your shoulder blades together to get the best results from this exercise.',
      'The arms should be elevated until they are parallel to the floor.',
      'Feel the contraction and slowly lower the weights back down to the starting position while inhaling.',
      'Repeat for the recommended amount of repetitions.',
    ],
  },
  {
    id: 'default-barbell-curl',
    name: 'Barbell Curl',
    muscleGroup: 'biceps',
    equipment: 'barbell',
    notes: 'Elbows pinned to the sides, no swinging',
    media: images('Barbell_Curl'),
    instructions: [
      'Stand up with your torso upright while holding a barbell at a shoulder-width grip. The palm of your hands should be facing forward and the elbows should be close to the torso. This will be your starting position.',
      'While holding the upper arms stationary, curl the weights forward while contracting the biceps as you breathe out. Tip: Only the forearms should move.',
      'Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second and squeeze the biceps hard.',
      'Slowly begin to bring the bar back to starting position as your breathe in.',
      'Repeat for the recommended amount of repetitions.',
    ],
  },
  {
    id: 'default-incline-dumbbell-curl',
    name: 'Incline Dumbbell Curl',
    muscleGroup: 'biceps',
    equipment: 'dumbbell',
    notes: 'Let the arms hang behind the body for a full stretch',
    media: images('Incline_Dumbbell_Curl'),
    instructions: [
      'Sit back on an incline bench with a dumbbell in each hand held at arms length. Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward. This will be your starting position.',
      'While holding the upper arm stationary, curl the weights forward while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second.',
      'Slowly begin to bring the dumbbells back to starting position as your breathe in.',
      'Repeat for the recommended amount of repetitions.',
    ],
  },
  {
    id: 'default-hammer-curl',
    name: 'Hammer Curl',
    muscleGroup: 'biceps',
    equipment: 'dumbbell',
    notes: 'Palms facing each other throughout',
    media: images('Hammer_Curls'),
    instructions: [
      'Stand up with your torso upright and a dumbbell on each hand being held at arms length. The elbows should be close to the torso.',
      'The palms of the hands should be facing your torso. This will be your starting position.',
      'Now, while holding your upper arm stationary, exhale and curl the weight forward while contracting the biceps. Continue to raise the weight until the biceps are fully contracted and the dumbbell is at shoulder level. Hold the contracted position for a brief moment as you squeeze the biceps. Tip: Focus on keeping the elbow stationary and only moving your forearm.',
      'After the brief pause, inhale and slowly begin the lower the dumbbells back down to the starting position.',
      'Repeat for the recommended amount of repetitions.',
    ],
  },
  {
    id: 'default-preacher-curl',
    name: 'Preacher Curl',
    muscleGroup: 'biceps',
    equipment: 'barbell',
    notes: 'Armpits on the pad, control the lowering',
    media: images('Preacher_Curl'),
    instructions: [
      'To perform this movement you will need a preacher bench and an E-Z bar. Grab the E-Z curl bar at the close inner handle (either have someone hand you the bar which is preferable or grab the bar from the front bar rest provided by most preacher benches). The palm of your hands should be facing forward and they should be slightly tilted inwards due to the shape of the bar.',
      'With the upper arms positioned against the preacher bench pad and the chest against it, hold the E-Z Curl Bar at shoulder length. This will be your starting position.',
      'As you breathe in, slowly lower the bar until your upper arm is extended and the biceps is fully stretched.',
      'As you exhale, use the biceps to curl the weight up until your biceps is fully contracted and the bar is at shoulder height. Squeeze the biceps hard and hold this position for a second.',
      'Repeat for the recommended amount of repetitions.',
    ],
  },
  {
    id: 'default-cable-curl',
    name: 'Cable Curl',
    muscleGroup: 'biceps',
    equipment: 'cable',
    notes: 'Constant tension, squeeze at the top',
    media: images('Standing_Biceps_Cable_Curl'),
    instructions: [
      'Stand up with your torso upright while holding a cable curl bar that is attached to a low pulley. Grab the cable bar at shoulder width and keep the elbows close to the torso. The palm of your hands should be facing up (supinated grip). This will be your starting position.',
      'While holding the upper arms stationary, curl the weights while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second as you squeeze the muscle.',
      'Slowly begin to bring the curl bar back to starting position as your breathe in.',
      'Repeat for the recommended amount of repetitions.',
    ],
  },
  {
    id: 'default-chin-up',
    name: 'Chin-Up',
    muscleGroup: 'biceps',
    equipment: 'bodyweight',
    notes: 'Palms facing you, pull the chin over the bar',
    media: images('Chin-Up'),
    instructions: [
      'Grab the pull-up bar with the palms facing your torso and a grip closer than the shoulder width.',
      'As you have both arms extended in front of you holding the bar at the chosen grip width, keep your torso as straight as possible while creating a curvature on your lower back and sticking your chest out. This is your starting position. Tip: Keeping the torso as straight as possible maximizes biceps stimulation while minimizing back involvement.',
      'As you breathe out, pull your torso up until your head is around the level of the pull-up bar. Concentrate on using the biceps muscles in order to perform the movement. Keep the elbows close to your body. Tip: The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar.',
      'After a second of squeezing the biceps in the contracted position, slowly lower your torso back to the starting position; when your arms are fully extended. Breathe in as you perform this portion of the movement.',
      'Repeat this motion for the prescribed amount of repetitions.',
    ],
  },
  {
    id: 'default-close-grip-bench-press',
    name: 'Close-Grip Bench Press',
    muscleGroup: 'triceps',
    equipment: 'barbell',
    notes: 'Hands shoulder-width, elbows tucked',
    media: images('Close-Grip_Barbell_Bench_Press'),
    instructions: [
      'Lie back on a flat bench. Using a close grip (around shoulder width), lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.',
      'As you breathe in, come down slowly until you feel the bar on your middle chest. Tip: Make sure that - as opposed to a regular bench press - you keep the elbows close to the torso at all times in order to maximize triceps involvement.',
      'After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your triceps muscles. Lock your arms in the contracted position, hold for a second and then start coming down slowly again. Tip: It should take at least twice as long to go down than to come up.',
      'Repeat the movement for the prescribed amount of repetitions.',
      'When you are done, place the bar back in the rack.',
    ],
  },
  {
    id: 'default-tricep-pushdown',
    name: 'Tricep Pushdown',
    muscleGroup: 'triceps',
    equipment: 'cable',
    notes: 'Elbows fixed at the sides, lock out at the bottom',
    media: images('Triceps_Pushdown'),
    instructions: [
      'Attach a straight or angled bar to a high pulley and grab with an overhand grip (palms facing down) at shoulder width.',
      'Standing upright with the torso straight and a very small inclination forward, bring the upper arms close to your body and perpendicular to the floor. The forearms should be pointing up towards the pulley as they hold the bar. This is your starting position.',
      'Using the triceps, bring the bar down until it touches the front of your thighs and the arms are fully extended perpendicular to the floor. The upper arms should always remain stationary next to your torso and only the forearms should move. Exhale as you perform this movement.',
      'After a second hold at the contracted position, bring the bar slowly up to the starting point. Breathe in as you perform this step.',
      'Repeat for the recommended amount of repetitions.',
    ],
  },
  {
    id: 'default-overhead-cable-extension',
    name: 'Overhead Cable Extension',
    muscleGroup: 'triceps',
    equipment: 'cable',
    notes: 'Elbows pointing forward, full stretch behind the head',
    media: images('Cable_Rope_Overhead_Triceps_Extension'),
    instructions: [
      'Attach a rope to the bottom pulley of the pulley machine.',
      'Grasping the rope with both hands, extend your arms with your hands directly above your head using a neutral grip (palms facing each other). Your elbows should be in close to your head and the arms should be perpendicular to the floor with the knuckles aimed at the ceiling. This will be your starting position.',
      'Slowly lower the rope behind your head as you hold the upper arms stationary. Inhale as you perform this movement and pause when your triceps are fully stretched.',
      'Return to the starting position by flexing your triceps as you breathe out.',
      'Repeat for the recommended amount of repetitions.',
    ],
  },
  {
    id: 'default-skull-crusher',
    name: 'Skull Crusher',
    muscleGroup: 'triceps',
    equipment: 'barbell',
    notes: 'Lower the bar towards the forehead, keep the upper arms still',
    media: images('EZ-Bar_Skullcrusher'),
    instructions: [
      'Using a close grip, lift the EZ bar and hold it with your elbows in as you lie on the bench. Your arms should be perpendicular to the floor. This will be your starting position.',
      'Keeping the upper arms stationary, lower the bar by allowing the elbows to flex. Inhale as you perform this portion of the movement. Pause once the bar is directly above the forehead.',
      'Lift the bar back to the starting position by extending the elbow and exhaling.',
      'Repeat.',
    ],
  },
  {
    id: 'default-dumbbell-kickback',
    name: 'Dumbbell Kickback',
    muscleGroup: 'triceps',
    equipment: 'dumbbell',
    notes: 'Upper arm parallel to the floor, straighten fully',
    media: images('Tricep_Dumbbell_Kickback'),
    instructions: [
      'Start with a dumbbell in each hand and your palms facing your torso. Keep your back straight with a slight bend in the knees and bend forward at the waist. Your torso should be almost parallel to the floor. Make sure to keep your head up. Your upper arms should be close to your torso and parallel to the floor. Your forearms should be pointed towards the floor as you hold the weights. There should be a 90-degree angle formed between your forearm and upper arm. This is your starting position.',
      'Now, while keeping your upper arms stationary, exhale and use your triceps to lift the weights until the arm is fully extended. Focus on moving the forearm.',
      'After a brief pause at the top contraction, inhale and slowly lower the dumbbells back down to the starting position.',
      'Repeat the movement for the prescribed amount of repetitions.',
    ],
  },
  {
    id: 'default-back-squat',
    name: 'Back Squat',
    muscleGroup: 'legs',
    equipment: 'barbell',
    notes: 'Brace, knees track over the toes, hips to at least knee height',
    media: images('Barbell_Squat'),
    instructions: [
      'This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack to just below shoulder level. Once the correct height is chosen and the bar is loaded, step under the bar and place the back of your shoulders (slightly below the neck) across it.',
      'Hold on to the bar using both arms at each side and lift it off the rack by first pushing with your legs and at the same time straightening your torso.',
      'Step away from the rack and position your legs using a shoulder width medium stance with the toes slightly pointed out. Keep your head up at all times and also maintain a straight back. This will be your starting position. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances discussed in the foot stances section).',
      'Begin to slowly lower the bar by bending the knees and hips as you maintain a straight posture with the head up. Continue down until the angle between the upper leg and the calves becomes slightly less than 90-degrees. Inhale as you perform this portion of the movement. Tip: If you performed the exercise correctly, the front of the knees should make an imaginary straight line with the toes that is perpendicular to the front. If your knees are past that imaginary line (if they are past your toes) then you are placing undue stress on the knee and the exercise has been performed incorrectly.',
      'Begin to raise the bar as you exhale by pushing the floor with the heel of your foot as you straighten the legs again and go back to the starting position.',
      'Repeat for the recommended amount of repetitions.',
    ],
  },
  {
    id: 'default-romanian-deadlift',
    name: 'Romanian Deadlift',
    muscleGroup: 'legs',
    equipment: 'barbell',
    notes: 'Soft knees, push the hips back until the hamstrings stretch',
    media: images('Romanian_Deadlift'),
    instructions: [
      'Put a barbell in front of you on the ground and grab it using a pronated (palms facing down) grip that a little wider than shoulder width. Tip: Depending on the weight used, you may need wrist wraps to perform the exercise and also a raised platform in order to allow for better range of motion.',
      'Bend the knees slightly and keep the shins vertical, hips back and back straight. This will be your starting position.',
      'Keeping your back and arms completely straight at all times, use your hips to lift the bar as you exhale. Tip: The movement should not be fast but steady and under control.',
      'Once you are standing completely straight up, lower the bar by pushing the hips back, only slightly bending the knees, unlike when squatting. Tip: Take a deep breath at the start of the movement and keep your chest up. Hold your breath as you lower and exhale as you complete the movement.',
      'Repeat for the recommended amount of repetitions.',
    ],
  },
  {
    id: 'default-leg-press',
    name: 'Leg Press',
    muscleGroup: 'legs',
    equipment: 'machine',
    notes: 'Lower back stays on the pad, don\'t lock the knees',
    media: images('Leg_Press'),
    instructions: [
      'Using a leg press machine, sit down on the machine and place your legs on the platform directly in front of you at a medium (shoulder width) foot stance. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section).',
      'Lower the safety bars holding the weighted platform in place and press the platform all the way up until your legs are fully extended in front of you. Tip: Make sure that you do not lock your knees. Your torso and the legs should make a perfect 90-degree angle. This will be your starting position.',
      'As you inhale, slowly lower the platform until your upper and lower legs make a 90-degree angle.',
      'Pushing mainly with the heels of your feet and using the quadriceps go back to the starting position as you exhale.',
      'Repeat for the recommended amount of repetitions and ensure to lock the safety pins properly once you are done. You do not want that platform falling on you fully loaded.',
    ],
  },
  {
    id: 'default-bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    muscleGroup: 'legs',
    equipment: 'dumbbell',
    notes: 'Rear foot on a bench, front knee over the mid-foot',
    media: images('Split_Squat_with_Dumbbells'),
    instructions: [
      'Position yourself into a staggered stance with the rear foot elevated and front foot forward.',
      'Hold a dumbbell in each hand, letting them hang at the sides. This will be your starting position.',
      'Begin by descending, flexing your knee and hip to lower your body down. Maintain good posture througout the movement. Keep the front knee in line with the foot as you perform the exercise.',
      'At the bottom of the movement, drive through the heel to extend the knee and hip to return to the starting position.',
    ],
  },
  {
    id: 'default-lying-leg-curl',
    name: 'Lying Leg Curl',
    muscleGroup: 'legs',
    equipment: 'machine',
    notes: 'Hips pressed into the pad, control the lowering',
    media: images('Lying_Leg_Curls'),
    instructions: [
      'Adjust the machine lever to fit your height and lie face down on the leg curl machine with the pad of the lever on the back of your legs (just a few inches under the calves). Tip: Preferably use a leg curl machine that is angled as opposed to flat since an angled position is more favorable for hamstrings recruitment.',
      'Keeping the torso flat on the bench, ensure your legs are fully stretched and grab the side handles of the machine. Position your toes straight (or you can also use any of the other two stances described on the foot positioning section). This will be your starting position.',
      'As you exhale, curl your legs up as far as possible without lifting the upper legs from the pad. Once you hit the fully contracted position, hold it for a second.',
      'As you inhale, bring the legs back to the initial position. Repeat for the recommended amount of repetitions.',
    ],
  },
  {
    id: 'default-standing-calf-raise',
    name: 'Standing Calf Raise',
    muscleGroup: 'legs',
    equipment: 'machine',
    notes: 'Full stretch at the bottom, pause at the top',
    media: images('Standing_Calf_Raises'),
    instructions: [
      'Adjust the padded lever of the calf raise machine to fit your height.',
      'Place your shoulders under the pads provided and position your toes facing forward (or using any of the two other positions described at the beginning of the chapter). The balls of your feet should be secured on top of the calf block with the heels extending off it. Push the lever up by extending your hips and knees until your torso is standing erect. The knees should be kept with a slight bend; never locked. Toes should be facing forward, outwards or inwards as described at the beginning of the chapter. This will be your starting position.',
      'Raise your heels as you breathe out by extending your ankles as high as possible and flexing your calf. Ensure that the knee is kept stationary at all times. There should be no bending at any time. Hold the contracted position by a second before you start to go back down.',
      'Go back slowly to the starting position as you breathe in by lowering your heels as you bend the ankles until calves are stretched.',
      'Repeat for the recommended amount of repetitions.',
    ],
  },
  {
    id: 'default-hanging-leg-raise',
    name: 'Hanging Leg Raise',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    notes: 'No swinging, curl the pelvis up',
    media: images('Hanging_Leg_Raise'),
    instructions: [
      'Hang from a chin-up bar with both arms extended at arms length in top of you using either a wide grip or a medium grip. The legs should be straight down with the pelvis rolled slightly backwards. This will be your starting position.',
      'Raise your legs until the torso makes a 90-degree angle with the legs. Exhale as you perform this movement and hold the contraction for a second or so.',
      'Go back slowly to the starting position as you breathe in.',
      'Repeat for the recommended amount of repetitions.',
    ],
  },
  {
    id: 'default-cable-crunch',
    name: 'Cable Crunch',
    muscleGroup: 'core',
    equipment: 'cable',
    notes: 'Round the spine, crunch the ribs towards the hips',
    media: images('Cable_Crunch'),
    instructions: [
      'Kneel below a high pulley that contains a rope attachment.',
      'Grasp cable rope attachment and lower the rope until your hands are placed next to your face.',
      'Flex your hips slightly and allow the weight to hyperextend the lower back. This will be your starting position.',
      'With the hips stationary, flex the waist as you contract the abs so that the elbows travel towards the middle of the thighs. Exhale as you perform this portion of the movement and hold the contraction for a second.',
      'Slowly return to the starting position as you inhale. Tip: Make sure that you keep constant tension on the abs throughout the movement. Also, do not choose a weight so heavy that the lower back handles the brunt of the work.',
      'Repeat for the recommended amount of repetitions.',
    ],
  },
  {
    id: 'default-ab-wheel-rollout',
    name: 'Ab Wheel Rollout',
    muscleGroup: 'core',
    equipment: 'other',
    notes: 'Keep the hips tucked, roll out only as far as you can control',
    media: images('Ab_Roller'),
    instructions: [
      'Hold the Ab Roller with both hands and kneel on the floor.',
      'Now place the ab roller on the floor in front of you so that you are on all your hands and knees (as in a kneeling push up position). This will be your starting position.',
      'Slowly roll the ab roller straight forward, stretching your body into a straight position. Tip: Go down as far as you can without touching the floor with your body. Breathe in during this portion of the movement.',
      'After a pause at the stretched position, start pulling yourself back to the starting position as you breathe out. Tip: Go slowly and keep your abs tight at all times.',
    ],
  },
  {
    id: 'default-plank',
    name: 'Plank',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    notes: 'Straight line from head to heels. Log seconds as reps',
    media: images('Plank'),
    instructions: [
      'Get into a prone position on the floor, supporting your weight on your toes and your forearms. Your arms are bent and directly below the shoulder.',
      'Keep your body straight at all times, and hold this position as long as possible. To increase difficulty, an arm or leg can be raised.',
    ],
  },
  {
    id: 'default-pallof-press',
    name: 'Pallof Press',
    muscleGroup: 'core',
    equipment: 'cable',
    notes: 'Resist the rotation, press straight out from the chest',
    media: images('Pallof_Press'),
    instructions: [
      'Connect a standard handle to a tower, and—if possible—position the cable to shoulder height. If not, a low pulley will suffice.',
      'With your side to the cable, grab the handle with both hands and step away from the tower. You should be approximately arm\'s length away from the pulley, with the tension of the weight on the cable.',
      'With your feet positioned hip-width apart and knees slightly bent, hold the cable to the middle of your chest. This will be your starting position.',
      'Press the cable away from your chest, fully extending both arms. You core should be tight and engaged.',
      'Hold the repetition for several seconds before returning to the starting position.',
      'At the conclusion of the set, repeat facing the other direction.',
    ],
  },
];
