// Start/end photos from free-exercise-db (https://github.com/yuhonas/free-exercise-db, public domain / Unlicense).
// Names, cues and instructions are our own: short imperative steps with checkable targets.
import { Exercise } from './types';

const IMAGE_BASE = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/';

function images(datasetId: string): Exercise['media'] {
  return [0, 1].map(i => ({ type: 'image' as const, src: `${IMAGE_BASE}${datasetId}/${i}.jpg` }));
}

export const DEFAULT_EXERCISES: Exercise[] = [
  {
    id: 'default-bench-press',
    name: 'Bench Press',
    muscleGroup: 'chest',
    equipment: 'barbell',
    notes: 'Shoulder blades pulled back, feet flat on the floor, bar to mid-chest.',
    media: images('Barbell_Bench_Press_-_Medium_Grip'),
    setup: 'Lie with your eyes under the bar, feet flat, shoulder blades squeezed back and down, hands just outside shoulder width.',
    instructions: [
      'Unrack the bar and hold it over your shoulders with straight arms.',
      'Lower the bar under control to your mid-chest, elbows about 45° from your body.',
      'Press up and slightly back towards your face until your arms are straight.',
    ],
  },
  {
    id: 'default-incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    muscleGroup: 'chest',
    equipment: 'dumbbell',
    notes: 'Bench at 30–45°, elbows at 45° to the torso.',
    media: images('Incline_Dumbbell_Press'),
    setup: 'Set the bench to 30–45° and sit back with a dumbbell on each thigh.',
    instructions: [
      'Kick the dumbbells up to your shoulders as you lie back, palms facing forward.',
      'Lower until the dumbbells are level with your upper chest, elbows slightly tucked.',
      'Press up and slightly together until your arms are straight.',
    ],
  },
  {
    id: 'default-chest-dip',
    name: 'Chest Dip',
    muscleGroup: 'chest',
    equipment: 'bodyweight',
    notes: 'Torso leaning forward 30° to load the chest.',
    media: images('Dips_-_Chest_Version'),
    setup: 'Support yourself on the bars with straight arms, torso leaning forward and knees slightly bent.',
    instructions: [
      'Lower until your upper arms are about parallel to the floor, letting your elbows flare a little.',
      'Press back up to straight arms, keeping the forward lean.',
    ],
  },
  {
    id: 'default-cable-crossover',
    name: 'Cable Crossover',
    muscleGroup: 'chest',
    equipment: 'cable',
    notes: 'Elbows bent 15–20°; hands meet in front of the lower chest.',
    media: images('Cable_Crossover'),
    setup: 'Set both pulleys high, take a handle in each hand and step forward into a split stance, arms out wide with a slight bend in the elbows.',
    instructions: [
      'Bring the handles down and together in front of your hips in a wide arc.',
      'Squeeze for a moment.',
      'Return slowly along the same arc until you feel a stretch across your chest.',
    ],
  },
  {
    id: 'default-machine-chest-press',
    name: 'Machine Chest Press',
    muscleGroup: 'chest',
    equipment: 'machine',
    notes: 'Handles level with mid-chest, shoulder blades against the pad.',
    media: images('Machine_Bench_Press'),
    setup: 'Adjust the seat so the handles are level with your mid-chest, and sit with your back against the pad and shoulder blades pulled back.',
    instructions: [
      'Press the handles forward until your arms are straight, without locking out hard.',
      'Return slowly until you feel a stretch in your chest.',
    ],
  },
  {
    id: 'default-push-up',
    name: 'Push-Up',
    muscleGroup: 'chest',
    equipment: 'bodyweight',
    notes: 'Body in a straight line from head to heels; chest to 5 cm above the floor.',
    media: images('Pushups'),
    setup: 'Hands slightly wider than your shoulders, body straight from head to heels, core braced and glutes squeezed.',
    instructions: [
      'Lower your chest to just above the floor, elbows about 45° from your body.',
      'Push back up to straight arms without letting your hips sag.',
    ],
  },
  {
    id: 'default-deadlift',
    name: 'Deadlift',
    muscleGroup: 'back',
    equipment: 'barbell',
    notes: 'Bar over mid-foot, back flat, bar in contact with the legs.',
    media: images('Barbell_Deadlift'),
    setup: 'Stand with the bar over your mid-foot, feet hip-width apart, and hinge down to grip it just outside your legs, shins touching the bar.',
    instructions: [
      'Flatten your back, breathe in and brace, then pull the slack out of the bar.',
      'Push the floor away and stand up with the bar close to your legs, hips and shoulders rising together.',
      'Lower by pushing your hips back, bending your knees once the bar passes them.',
    ],
  },
  {
    id: 'default-pull-up',
    name: 'Pull-Up',
    muscleGroup: 'back',
    equipment: 'bodyweight',
    notes: 'Start with straight arms; finish with the chin above the bar.',
    media: images('Pullups'),
    setup: 'Hang from the bar with an overhand grip slightly wider than your shoulders.',
    instructions: [
      'Pull your shoulder blades down, then pull your chest towards the bar.',
      'Go up until your chin clears the bar.',
      'Lower all the way to straight arms under control.',
    ],
  },
  {
    id: 'default-barbell-row',
    name: 'Barbell Row',
    muscleGroup: 'back',
    equipment: 'barbell',
    notes: 'Torso at 45° to the floor, bar to the lower ribs.',
    media: images('Bent_Over_Barbell_Row'),
    setup: 'Hold the bar with an overhand grip, hands just outside your knees, and hinge until your torso is at about 45°, back flat and knees soft.',
    instructions: [
      'Pull the bar to your lower ribs, driving your elbows back.',
      'Lower under control without letting your torso rise.',
    ],
  },
  {
    id: 'default-lat-pulldown',
    name: 'Lat Pulldown',
    muscleGroup: 'back',
    equipment: 'cable',
    notes: 'Torso leaning back 15°, bar to the upper chest.',
    media: images('Wide-Grip_Lat_Pulldown'),
    setup: 'Lock your thighs under the knee pad and grip the bar wider than your shoulders.',
    instructions: [
      'Lean back slightly with your chest up.',
      'Pull the bar to your upper chest, driving your elbows down and back.',
      'Let the bar rise slowly until your arms are straight.',
    ],
  },
  {
    id: 'default-seated-cable-row',
    name: 'Seated Cable Row',
    muscleGroup: 'back',
    equipment: 'cable',
    notes: 'Torso upright, handle to the navel.',
    media: images('Seated_Cable_Rows'),
    setup: 'Sit with your feet on the platform and knees slightly bent, chest up, holding the handle with straight arms.',
    instructions: [
      'Pull the handle to your stomach, squeezing your shoulder blades together.',
      'Return slowly, letting your shoulders reach forward without rounding your lower back.',
    ],
  },
  {
    id: 'default-one-arm-dumbbell-row',
    name: 'One-Arm Dumbbell Row',
    muscleGroup: 'back',
    equipment: 'dumbbell',
    notes: 'Back flat, dumbbell to the hip.',
    media: images('One-Arm_Dumbbell_Row'),
    setup: 'Put one knee and the same hand on a bench, back flat, holding the dumbbell in your free hand with your arm straight.',
    instructions: [
      'Pull the dumbbell towards your hip, keeping your elbow close to your body.',
      'Lower under control to a full stretch.',
      'Switch sides after the set.',
    ],
  },
  {
    id: 'default-overhead-press',
    name: 'Overhead Press',
    muscleGroup: 'shoulders',
    equipment: 'barbell',
    notes: 'Glutes and abdominals contracted; bar moves in a vertical line.',
    media: images('Standing_Military_Press'),
    setup: 'Hold the bar at your collarbones, hands just outside your shoulders, elbows slightly in front of the bar, glutes squeezed and core braced.',
    instructions: [
      'Press the bar straight up, moving your head back to let it pass.',
      'Finish with the bar over your mid-foot and your head through.',
      'Lower under control to your collarbones.',
    ],
  },
  {
    id: 'default-dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    muscleGroup: 'shoulders',
    equipment: 'dumbbell',
    notes: 'Lower to ear height; lower back against the bench.',
    media: images('Dumbbell_Shoulder_Press'),
    setup: 'Sit on a bench with back support, dumbbells at shoulder height, palms facing forward.',
    instructions: [
      'Press the dumbbells up until your arms are straight overhead.',
      'Lower until the dumbbells are at about ear height.',
      'Keep your lower back against the pad throughout.',
    ],
  },
  {
    id: 'default-lateral-raise',
    name: 'Lateral Raise',
    muscleGroup: 'shoulders',
    equipment: 'dumbbell',
    notes: 'Elbows bent 10–15°; raise to shoulder height.',
    media: images('Side_Lateral_Raise'),
    setup: 'Stand with a dumbbell in each hand at your sides, elbows slightly bent.',
    instructions: [
      'Raise your arms out to the sides, leading with your elbows.',
      'Stop at shoulder height.',
      'Lower slowly, and don\'t swing to start the next rep.',
    ],
  },
  {
    id: 'default-face-pull',
    name: 'Face Pull',
    muscleGroup: 'shoulders',
    equipment: 'cable',
    notes: 'Rope at face height; hands finish beside the ears.',
    media: images('Face_Pull'),
    setup: 'Attach a rope to a cable at face height, hold the ends with palms facing in, and step back until the cable is under tension.',
    instructions: [
      'Pull the rope towards your face, separating your hands so they end up beside your ears.',
      'Squeeze your upper back, then return slowly.',
    ],
  },
  {
    id: 'default-reverse-fly',
    name: 'Reverse Fly',
    muscleGroup: 'shoulders',
    equipment: 'dumbbell',
    notes: 'Torso parallel to the floor, elbows bent 10–15°.',
    media: images('Reverse_Flyes'),
    setup: 'Hold a dumbbell in each hand and hinge forward until your torso is nearly parallel to the floor, dumbbells hanging below your chest with soft elbows.',
    instructions: [
      'Raise your arms out to the sides until they are level with your body.',
      'Squeeze your shoulder blades together, then lower slowly.',
    ],
  },
  {
    id: 'default-barbell-curl',
    name: 'Barbell Curl',
    muscleGroup: 'biceps',
    equipment: 'barbell',
    notes: 'Elbows fixed at the sides; torso does not move.',
    media: images('Barbell_Curl'),
    setup: 'Stand holding the bar with an underhand, shoulder-width grip, elbows pinned to your sides.',
    instructions: [
      'Curl the bar up to your shoulders without swinging your body.',
      'Lower slowly until your arms are fully straight.',
    ],
  },
  {
    id: 'default-incline-dumbbell-curl',
    name: 'Incline Dumbbell Curl',
    muscleGroup: 'biceps',
    equipment: 'dumbbell',
    notes: 'Bench at 45–60°; arms hang vertically at the start.',
    media: images('Incline_Dumbbell_Curl'),
    setup: 'Set a bench to about 45° and sit back with a dumbbell in each hand, arms hanging straight down behind your body, palms forward.',
    instructions: [
      'Curl the dumbbells up without moving your upper arms.',
      'Lower slowly to a full stretch.',
    ],
  },
  {
    id: 'default-hammer-curl',
    name: 'Hammer Curl',
    muscleGroup: 'biceps',
    equipment: 'dumbbell',
    notes: 'Palms face each other throughout.',
    media: images('Hammer_Curls'),
    setup: 'Stand with a dumbbell in each hand at your sides, palms facing each other, elbows pinned to your sides.',
    instructions: [
      'Curl the dumbbells up, keeping your palms facing each other.',
      'Lower slowly until your arms are straight.',
    ],
  },
  {
    id: 'default-preacher-curl',
    name: 'Preacher Curl',
    muscleGroup: 'biceps',
    equipment: 'barbell',
    notes: 'Upper arms on the pad; lower until the arms are straight.',
    media: images('Preacher_Curl'),
    setup: 'Sit at the preacher bench with your armpits against the top of the pad, holding the bar with an underhand, shoulder-width grip.',
    instructions: [
      'Curl the bar up until your forearms are nearly vertical.',
      'Lower slowly until your arms are almost straight, without bouncing at the bottom.',
    ],
  },
  {
    id: 'default-cable-curl',
    name: 'Cable Curl',
    muscleGroup: 'biceps',
    equipment: 'cable',
    notes: 'Elbows fixed at the sides.',
    media: images('Standing_Biceps_Cable_Curl'),
    setup: 'Attach a straight bar to a low pulley, hold it with an underhand grip and stand tall with your elbows at your sides.',
    instructions: [
      'Curl the bar up to your shoulders and squeeze.',
      'Lower slowly, keeping tension on the cable.',
    ],
  },
  {
    id: 'default-chin-up',
    name: 'Chin-Up',
    muscleGroup: 'biceps',
    equipment: 'bodyweight',
    notes: 'Palms facing the body; chin above the bar.',
    media: images('Chin-Up'),
    setup: 'Hang from the bar with an underhand grip, hands shoulder-width apart.',
    instructions: [
      'Pull your shoulder blades down, then pull yourself up.',
      'Go up until your chin clears the bar.',
      'Lower all the way to straight arms under control.',
    ],
  },
  {
    id: 'default-close-grip-bench-press',
    name: 'Close-Grip Bench Press',
    muscleGroup: 'triceps',
    equipment: 'barbell',
    notes: 'Hands shoulder-width apart; elbows within 30° of the torso.',
    media: images('Close-Grip_Barbell_Bench_Press'),
    setup: 'Lie on the bench and grip the bar with your hands about shoulder-width apart, shoulder blades pulled back.',
    instructions: [
      'Unrack the bar and hold it over your shoulders with straight arms.',
      'Lower the bar to your lower chest, keeping your elbows tucked close to your body.',
      'Press back up until your arms are straight.',
    ],
  },
  {
    id: 'default-tricep-pushdown',
    name: 'Tricep Pushdown',
    muscleGroup: 'triceps',
    equipment: 'cable',
    notes: 'Upper arms fixed at the sides; arms straight at the bottom.',
    media: images('Triceps_Pushdown'),
    setup: 'Attach a bar or rope to a high pulley, grip it with your elbows at your sides and lean forward slightly.',
    instructions: [
      'Push down until your arms are fully straight, keeping your elbows still.',
      'Let the weight rise slowly until your forearms pass horizontal.',
    ],
  },
  {
    id: 'default-overhead-cable-extension',
    name: 'Overhead Cable Extension',
    muscleGroup: 'triceps',
    equipment: 'cable',
    notes: 'Elbows pointing forward; hands behind the head at the bottom.',
    media: images('Cable_Rope_Overhead_Triceps_Extension'),
    setup: 'Attach a rope to a low pulley, hold it behind your head facing away from the machine, and step into a split stance with your elbows pointing forward.',
    instructions: [
      'Straighten your arms overhead.',
      'Lower slowly behind your head to a full stretch, keeping your upper arms still.',
    ],
  },
  {
    id: 'default-skull-crusher',
    name: 'Skull Crusher',
    muscleGroup: 'triceps',
    equipment: 'barbell',
    notes: 'Upper arms vertical and fixed.',
    media: images('EZ-Bar_Skullcrusher'),
    setup: 'Lie on a bench holding an EZ-bar over your chest with straight arms, tilted slightly back towards your head.',
    instructions: [
      'Bend only at the elbows to lower the bar towards your forehead.',
      'Straighten your arms back to the start without moving your upper arms.',
    ],
  },
  {
    id: 'default-dumbbell-kickback',
    name: 'Dumbbell Kickback',
    muscleGroup: 'triceps',
    equipment: 'dumbbell',
    notes: 'Upper arm parallel to the floor; arm straight at the top.',
    media: images('Tricep_Dumbbell_Kickback'),
    setup: 'Put one knee and the same hand on a bench, back flat, and raise the dumbbell until your upper arm is parallel to the floor, elbow bent at 90°.',
    instructions: [
      'Straighten your arm back until it is fully extended.',
      'Lower under control, keeping your upper arm still.',
      'Switch sides after the set.',
    ],
  },
  {
    id: 'default-back-squat',
    name: 'Back Squat',
    muscleGroup: 'legs',
    equipment: 'barbell',
    notes: 'Knees in line with the toes; hips to knee height or lower.',
    media: images('Barbell_Squat'),
    setup: 'Set the bar across your upper back and step back, feet about shoulder-width apart, toes slightly out.',
    instructions: [
      'Breathe in and brace your core.',
      'Sit down and back, knees tracking over your toes, until your hips are at least level with your knees.',
      'Drive up through your whole foot, keeping your chest up.',
    ],
  },
  {
    id: 'default-romanian-deadlift',
    name: 'Romanian Deadlift',
    muscleGroup: 'legs',
    equipment: 'barbell',
    notes: 'Knees bent 15–20°; hips move back; bar in contact with the legs.',
    media: images('Romanian_Deadlift'),
    setup: 'Stand holding the bar at your hips with a shoulder-width grip, knees slightly bent.',
    instructions: [
      'Push your hips back and let the bar slide down your thighs, back flat.',
      'Stop when you feel a strong stretch in your hamstrings, usually just below the knees.',
      'Drive your hips forward to stand back up.',
    ],
  },
  {
    id: 'default-leg-press',
    name: 'Leg Press',
    muscleGroup: 'legs',
    equipment: 'machine',
    notes: 'Lower back against the pad; knees not locked at the top.',
    media: images('Leg_Press'),
    setup: 'Sit with your back flat against the pad, feet shoulder-width apart on the platform, and release the safety handles.',
    instructions: [
      'Lower the platform until your knees are at about 90°, without your lower back lifting off the pad.',
      'Press back up without locking your knees.',
    ],
  },
  {
    id: 'default-bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    muscleGroup: 'legs',
    equipment: 'dumbbell',
    notes: 'Rear foot on a bench; front knee above the middle of the foot.',
    media: images('Split_Squat_with_Dumbbells'),
    setup: 'Stand a long stride in front of a bench with a dumbbell in each hand, and rest the top of your back foot on the bench.',
    instructions: [
      'Lower straight down until your back knee nearly touches the floor, keeping your front knee over your mid-foot.',
      'Push through your front foot to stand, torso upright or leaning slightly forward.',
      'Switch legs after the set.',
    ],
  },
  {
    id: 'default-lying-leg-curl',
    name: 'Lying Leg Curl',
    muscleGroup: 'legs',
    equipment: 'machine',
    notes: 'Hips pressed against the pad.',
    media: images('Lying_Leg_Curls'),
    setup: 'Lie face down on the machine with the pad just above your heels, knees just off the bench, and press your hips into the pad.',
    instructions: [
      'Curl your heels towards your glutes as far as you can.',
      'Lower slowly until your legs are almost straight.',
    ],
  },
  {
    id: 'default-standing-calf-raise',
    name: 'Standing Calf Raise',
    muscleGroup: 'legs',
    equipment: 'machine',
    notes: 'Heels below the platform at the bottom; 1-second pause at the top.',
    media: images('Standing_Calf_Raises'),
    setup: 'Stand with the balls of your feet on the platform and the pads on your shoulders.',
    instructions: [
      'Lower your heels as far as you can for a full stretch.',
      'Rise onto your toes as high as you can.',
      'Pause at the top, then lower slowly.',
    ],
  },
  {
    id: 'default-hanging-leg-raise',
    name: 'Hanging Leg Raise',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    notes: 'No swinging; tilt the pelvis up at the top.',
    media: images('Hanging_Leg_Raise'),
    setup: 'Hang from a bar with straight arms and your shoulders engaged.',
    instructions: [
      'Raise your legs by curling your pelvis up, with knees bent or straight.',
      'Lift until your thighs are at least parallel to the floor.',
      'Lower slowly without swinging.',
    ],
  },
  {
    id: 'default-cable-crunch',
    name: 'Cable Crunch',
    muscleGroup: 'core',
    equipment: 'cable',
    notes: 'Hips stay still; the ribs move towards the pelvis.',
    media: images('Cable_Crunch'),
    setup: 'Attach a rope to a high pulley and kneel below it, holding the rope beside your head.',
    instructions: [
      'Keeping your hips still, crunch down by rounding your spine, bringing your ribs towards your hips.',
      'Return slowly until your abs are stretched.',
    ],
  },
  {
    id: 'default-ab-wheel-rollout',
    name: 'Ab Wheel Rollout',
    muscleGroup: 'core',
    equipment: 'other',
    notes: 'Pelvis tucked; stop before the lower back arches.',
    media: images('Ab_Roller'),
    setup: 'Kneel holding the ab wheel on the floor below your shoulders, core braced and hips tucked under.',
    instructions: [
      'Roll forward slowly, only as far as you can without your lower back sagging.',
      'Pull back to the start using your abs.',
    ],
  },
  {
    id: 'default-plank',
    name: 'Plank',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    notes: 'Straight line from head to heels. Log seconds as reps.',
    media: images('Plank'),
    setup: 'Rest on your forearms and toes, elbows under your shoulders, body in a straight line from head to heels.',
    instructions: [
      'Brace your core and squeeze your glutes.',
      'Hold for the target time, breathing steadily.',
      'Log seconds as reps.',
    ],
  },
  {
    id: 'default-pallof-press',
    name: 'Pallof Press',
    muscleGroup: 'core',
    equipment: 'cable',
    notes: 'The torso does not rotate.',
    media: images('Pallof_Press'),
    setup: 'Set a cable handle at chest height, stand side-on to the machine and hold the handle at your chest, stepping away until there is tension.',
    instructions: [
      'Press the handle straight out and hold for a moment, resisting being twisted towards the machine.',
      'Bring the handle back to your chest.',
      'Switch sides after the set.',
    ],
  },
];

/**
 * Earlier versions of each default cue. A stored cue that still matches one of these
 * was never edited by the user, so GymStore.load() replaces it with the current cue.
 */
export const REPLACED_DEFAULT_CUES: Record<string, string[]> = {
  'default-bench-press': ['Shoulder blades squeezed together, feet planted, lower the bar to mid-chest'],
  'default-incline-dumbbell-press': ['Bench at 30–45°, elbows about 45° from the body'],
  'default-chest-dip': ['Lean forward and let the elbows flare slightly to bias the chest'],
  'default-cable-crossover': ['Slight bend in the elbows, squeeze the hands together in front of the chest'],
  'default-machine-chest-press': ['Handles level with mid-chest, don\'t let the shoulders roll forward'],
  'default-push-up': ['Body in a straight line, chest to just above the floor'],
  'default-deadlift': ['Bar over mid-foot, flat back, push the floor away'],
  'default-pull-up': ['Start from a dead hang, pull the chest towards the bar'],
  'default-barbell-row': ['Hinge to about 45°, pull the bar to the lower ribs'],
  'default-lat-pulldown': ['Lean back slightly, pull the bar to the upper chest'],
  'default-seated-cable-row': ['Chest up, pull to the stomach, squeeze the shoulder blades'],
  'default-one-arm-dumbbell-row': ['Flat back, pull the dumbbell towards the hip'],
  'default-overhead-press': ['Glutes tight, press straight up and move the head through at the top'],
  'default-dumbbell-shoulder-press': ['Lower to ear height, press without arching the lower back'],
  'default-lateral-raise': ['Lead with the elbows, stop at shoulder height'],
  'default-face-pull': ['Rope at face height, pull apart towards the ears'],
  'default-reverse-fly': ['Hinge forward, raise the arms out wide with soft elbows'],
  'default-barbell-curl': ['Elbows pinned to the sides, no swinging'],
  'default-incline-dumbbell-curl': ['Let the arms hang behind the body for a full stretch'],
  'default-hammer-curl': ['Palms facing each other throughout'],
  'default-preacher-curl': ['Armpits on the pad, control the lowering'],
  'default-cable-curl': ['Constant tension, squeeze at the top'],
  'default-chin-up': ['Palms facing you, pull the chin over the bar'],
  'default-close-grip-bench-press': ['Hands shoulder-width, elbows tucked'],
  'default-tricep-pushdown': ['Elbows fixed at the sides, lock out at the bottom'],
  'default-overhead-cable-extension': ['Elbows pointing forward, full stretch behind the head'],
  'default-skull-crusher': ['Lower the bar towards the forehead, keep the upper arms still'],
  'default-dumbbell-kickback': ['Upper arm parallel to the floor, straighten fully'],
  'default-back-squat': ['Brace, knees track over the toes, hips to at least knee height'],
  'default-romanian-deadlift': ['Soft knees, push the hips back until the hamstrings stretch'],
  'default-leg-press': ['Lower back stays on the pad, don\'t lock the knees'],
  'default-bulgarian-split-squat': ['Rear foot on a bench, front knee over the mid-foot'],
  'default-lying-leg-curl': ['Hips pressed into the pad, control the lowering'],
  'default-standing-calf-raise': ['Full stretch at the bottom, pause at the top'],
  'default-hanging-leg-raise': ['No swinging, curl the pelvis up'],
  'default-cable-crunch': ['Round the spine, crunch the ribs towards the hips'],
  'default-ab-wheel-rollout': ['Keep the hips tucked, roll out only as far as you can control'],
  'default-plank': ['Straight line from head to heels. Log seconds as reps'],
  'default-pallof-press': ['Resist the rotation, press straight out from the chest'],
};
